defmodule SecretHub.Shared.Schemas.ClientAuthCrl do
  @moduledoc """
  Schema for signed Certificate Revocation Lists (CRLs) generated by the
  Client Authentication PKI Authority.
  """

  use Ecto.Schema
  import Ecto.Changeset

  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id
  @fingerprint_format ~r/\A[0-9a-f]{64}\z/

  schema "client_auth_crls" do
    field(:crl_number, :integer)
    field(:generation, :integer)
    field(:crl_pem, :string)
    field(:crl_der_sha256, :string)
    field(:this_update, :utc_datetime)
    field(:next_update, :utc_datetime)
    field(:revoked_count, :integer, default: 0)

    belongs_to(:authority, SecretHub.Shared.Schemas.ClientAuthAuthority,
      foreign_key: :authority_id
    )

    belongs_to(:issuer_certificate, SecretHub.Shared.Schemas.Certificate,
      foreign_key: :issuer_certificate_id
    )

    timestamps(type: :utc_datetime)
  end

  @type t :: %__MODULE__{}

  def changeset(crl, attrs) do
    crl
    |> cast(attrs, [
      :authority_id,
      :issuer_certificate_id,
      :crl_number,
      :generation,
      :crl_pem,
      :crl_der_sha256,
      :this_update,
      :next_update,
      :revoked_count
    ])
    |> validate_required([
      :authority_id,
      :issuer_certificate_id,
      :crl_number,
      :generation,
      :crl_pem,
      :crl_der_sha256,
      :this_update,
      :next_update,
      :revoked_count
    ])
    |> validate_format(:crl_der_sha256, @fingerprint_format,
      message: "must be a 64-character lowercase hexadecimal SHA-256 string"
    )
    |> validate_update_dates()
    |> unique_constraint([:authority_id, :crl_number])
    |> unique_constraint([:authority_id, :generation])
  end

  defp validate_update_dates(changeset) do
    this_update = get_field(changeset, :this_update)
    next_update = get_field(changeset, :next_update)

    if this_update && next_update && DateTime.compare(this_update, next_update) != :lt do
      add_error(changeset, :next_update, "must be strictly after this_update")
    else
      changeset
    end
  end
end
