apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "secrethub.fullname" . }}-config
  labels:
    {{- include "secrethub.labels" . | nindent 4 }}
data:
  # Phoenix configuration
  PHX_HOST: {{ .Values.core.env.PHX_HOST | quote }}
  PHX_PORT: {{ .Values.core.env.PHX_PORT | quote }}
  MIX_ENV: {{ .Values.core.env.MIX_ENV | quote }}

  # Erlang/Elixir settings
  ELIXIR_ERL_OPTIONS: {{ .Values.core.env.ELIXIR_ERL_OPTIONS | quote }}

  {{- if .Values.kms.enabled }}
  # KMS configuration
  KMS_REGION: {{ .Values.kms.region | quote }}
  KMS_KEY_ID: {{ .Values.kms.keyId | quote }}
  {{- if .Values.kms.endpoint }}
  KMS_ENDPOINT: {{ .Values.kms.endpoint | quote }}
  {{- end }}
  {{- end }}

  {{- if .Values.monitoring.prometheus.enabled }}
  # Prometheus metrics
  PROMETHEUS_PORT: {{ .Values.monitoring.prometheus.port | quote }}
  PROMETHEUS_PATH: {{ .Values.monitoring.prometheus.path | quote }}
  {{- end }}

  # Audit log retention
  AUDIT_HOT_RETENTION_DAYS: {{ .Values.audit.hotRetentionDays | quote }}
  AUDIT_WARM_RETENTION_DAYS: {{ .Values.audit.warmRetentionDays | quote }}
  AUDIT_COLD_RETENTION_DAYS: {{ .Values.audit.coldRetentionDays | quote }}
