apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "secrethub.fullname" . }}
  labels:
    {{- include "secrethub.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "secrethub.fullname" . }}
  replicas: {{ .Values.core.replicaCount }}
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      {{- include "secrethub.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        {{- include "secrethub.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "secrethub.serviceAccountName" . }}
      securityContext:
        runAsNonRoot: {{ .Values.core.securityContext.runAsNonRoot }}
        runAsUser: {{ .Values.core.securityContext.runAsUser }}
        fsGroup: {{ .Values.core.securityContext.fsGroup }}
      {{- with .Values.core.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.core.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.core.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: secrethub-core
          image: "{{ .Values.core.image.repository }}:{{ .Values.core.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.core.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 4000
              protocol: TCP
            {{- if .Values.monitoring.prometheus.enabled }}
            - name: metrics
              containerPort: {{ .Values.monitoring.prometheus.port }}
              protocol: TCP
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "secrethub.fullname" . }}-config
            {{- if .Values.secrets.create }}
            - secretRef:
                name: {{ include "secrethub.fullname" . }}-secrets
            {{- end }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          livenessProbe:
            {{- toYaml .Values.core.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.core.readinessProbe | nindent 12 }}
          startupProbe:
            {{- toYaml .Values.core.startupProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.core.resources | nindent 12 }}
          securityContext:
            capabilities:
              {{- toYaml .Values.core.securityContext.capabilities | nindent 14 }}
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
          volumeMounts:
            - name: data
              mountPath: /app/data
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
  {{- if .Values.core.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
        {{- with .Values.core.persistence.annotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
          - {{ .Values.core.persistence.accessMode }}
        {{- if (include "secrethub.storageClass" .) }}
        storageClassName: {{ include "secrethub.storageClass" . }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.core.persistence.size }}
  {{- else }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  {{- end }}
