defmodule SecretHub.Human.Attachments.Storage do
  @moduledoc "Ciphertext-only storage boundary; identifiers are generated by Human, never paths from clients."
  @callback put(binary(), binary(), keyword()) :: :ok | {:error, atom()}
  @callback get(binary(), keyword()) :: {:ok, binary()} | {:error, atom()}
  @callback delete(binary(), keyword()) :: :ok | {:error, atom()}
  @callback list(keyword()) :: {:ok, [{binary(), integer()}]} | {:error, atom()}
end
