---
apiVersion: v1
kind: ConfigMap
metadata:
  name: secrethub-config
  namespace: secrethub
  labels:
    app: secrethub-core
data:
  # PostgreSQL connection
  postgres_host: "postgres.secrethub.svc.cluster.local"
  postgres_port: "5432"
  postgres_database: "secrethub_prod"

  # Redis connection
  redis_url: "redis://redis.secrethub.svc.cluster.local:6379"

  # AWS configuration for auto-unseal
  aws_region: "us-east-1"
  auto_unseal_enabled: "true"

  # Application configuration
  phx_host: "secrethub-core.secrethub.svc.cluster.local"
  phx_port: "4000"
  mix_env: "prod"

  # Cluster configuration
  cluster_enabled: "true"
  cluster_size: "3"

  # Health check configuration
  health_check_interval: "30"
  readiness_timeout: "10"
  liveness_timeout: "10"
