name: Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: secrethub
          POSTGRES_PASSWORD: secrethub_test_password
          POSTGRES_DB: secrethub_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.18'
          otp-version: '28'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Install dependencies
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get

      - name: Create database
        env:
          MIX_ENV: test
          DATABASE_URL: postgresql://secrethub:secrethub_test_password@localhost:5432/secrethub_test
        run: mix ecto.create

      - name: Run migrations
        env:
          MIX_ENV: test
          DATABASE_URL: postgresql://secrethub:secrethub_test_password@localhost:5432/secrethub_test
        run: mix ecto.migrate

      - name: Run tests
        env:
          MIX_ENV: test
          DATABASE_URL: postgresql://secrethub:secrethub_test_password@localhost:5432/secrethub_test
          REDIS_URL: redis://localhost:6379
        run: mix test

      - name: Generate coverage report
        if: success()
        env:
          MIX_ENV: test
          DATABASE_URL: postgresql://secrethub:secrethub_test_password@localhost:5432/secrethub_test
          REDIS_URL: redis://localhost:6379
        run: mix coveralls.html

      - name: Upload coverage report
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: cover/
